version: "3.9"

services:
  app:
    container_name: cms-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "python3 manage.py collectstatic --noinput && gunicorn cms_is2.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - static_volume:/app/staticfiles
volumes:
  static_volume: